export const FETCH_CASES_REQUEST = "FETCH_CASES_REQUEST";
export const FETCH_CASES_SUCCESS = "FETCH_CASES_SUCCESS";
export const FETCH_CASES_FAILURE = "FETCH_CASES_FAILURE";

export const CREATE_CASE_REQUEST = "CREATE_CASE_REQUEST";
export const CREATE_CASE_SUCCESS = "CREATE_CASE_SUCCESS";
export const CREATE_CASE_FAILURE = "CREATE_CASE_FAILURE";

export const CREATE_CASE_PUBLIC_REQUEST = "CREATE_CASE_PUBLIC_REQUEST";
export const CREATE_CASE_PUBLIC_SUCCESS = "CREATE_CASE_PUBLIC_SUCCESS";
export const CREATE_CASE_PUBLIC_FAILURE = "CREATE_CASE_PUBLIC_FAILURE";

export const EDIT_CASE_REQUEST = "EDIT_CASE_REQUEST";
export const EDIT_CASE_SUCCESS = "EDIT_CASE_SUCCESS";
export const EDIT_CASE_FAILURE = "EDIT_CASE_FAILURE";

export const DELETE_CASE_REQUEST = "DELETE_CASE_REQUEST";
export const DELETE_CASE_SUCCESS = "DELETE_CASE_SUCCESS";
export const DELETE_CASE_FAILURE = "DELETE_CASE_FAILURE";

export const GET_ONE_CASE_REQUEST = "GET_ONE_CASE_REQUEST";
export const GET_ONE_CASE_SUCCESS = "GET_ONE_CASE_SUCCESS";
export const GET_ONE_CASE_FAILURE = "GET_ONE_CASE_FAILURE";

export const FETCH_OFFICERS_REQUEST = "FETCH_OFFICERS_REQUEST";
export const FETCH_OFFICERS_SUCCESS = "FETCH_OFFICERS_SUCCESS";
export const FETCH_OFFICERS_FAILURE = "FETCH_OFFICERS_FAILURE";

export const DELETE_OFFICER_REQUEST = "DELETE_OFFICER_REQUEST";
export const DELETE_OFFICER_SUCCESS = "DELETE_OFFICER_SUCCESS";
export const DELETE_OFFICER_FAILURE = "DELETE_OFFICER_FAILURE";

export const GET_ONE_OFFICER_REQUEST = "GET_ONE_OFFICER_REQUEST";
export const GET_ONE_OFFICER_SUCCESS = "GET_ONE_OFFICER_SUCCESS";
export const GET_ONE_OFFICER_FAILURE = "GET_ONE_OFFICER_FAILURE";

export const EDIT_OFFICER_REQUEST = "EDIT_OFFICER_REQUEST";
export const EDIT_OFFICER_SUCCESS = "EDIT_OFFICER_SUCCESS";
export const EDIT_OFFICER_FAILURE = "EDIT_OFFICER_FAILURE";

export const CREATE_OFFICER_REQUEST = "CREATE_OFFICER_REQUEST";
export const CREATE_OFFICER_SUCCESS = "CREATE_OFFICER_SUCCESS";
export const CREATE_OFFICER_FAILURE = "CREATE_OFFICER_FAILURE";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";

export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";

export const ON_CLICK_MESSAGE_BUTTON = "ON_CLICK_MESSAGE_BUTTON";
export const ON_CLICK_MODAL_BUTTON = "ON_CLICK_MODAL_BUTTON";